from typing import Any, Protocol


class CountyAdapter(Protocol):
    county_id: str
    def fetch(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def parse(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def normalize(self, *args: Any, **kwargs: Any) -> dict[str, list[dict]]: ...
