CREATE TABLE IF NOT EXISTS county_configs (
  county_config_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  county_id text NOT NULL REFERENCES counties(county_id),
  tax_year integer REFERENCES tax_years(tax_year),
  appraisal_district_id uuid REFERENCES appraisal_districts(appraisal_district_id),
  parser_module_name text,
  protest_deadline_rule text,
  homestead_cap_percent numeric(7,4),
  data_refresh_frequency text,
  quote_enabled boolean NOT NULL DEFAULT true,
  market_comp_month_window integer NOT NULL DEFAULT 12,
  market_comp_same_neighborhood_preferred boolean NOT NULL DEFAULT true,
  market_comp_living_area_tolerance_pct numeric(7,4) NOT NULL DEFAULT 0.25,
  market_comp_year_built_tolerance integer NOT NULL DEFAULT 15,
  equity_comp_living_area_tolerance_pct numeric(7,4) NOT NULL DEFAULT 0.20,
  equity_comp_year_built_tolerance integer NOT NULL DEFAULT 10,
  minimum_gap_threshold_pct numeric(7,4) NOT NULL DEFAULT 0.05,
  minimum_savings_threshold numeric(14,2) NOT NULL DEFAULT 300.00,
  public_quote_enabled boolean NOT NULL DEFAULT true,
  restricted_sales_enabled boolean NOT NULL DEFAULT false,
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (county_id, tax_year)
);
